### ISSUE TITLE
Unable to run uribeacon

### ISSUE THREAD

**Issue by IgorGanapolsky** [tigoe/BluetoothLE-Examples#5]
Hi,
I am trying to utilize your uribeacon sample.  I execute `npm install`, and receive this error:
> npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for uri-beacon@0.2.4: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})
npm ERR! notsup Valid OS:    linux
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: x64
npm ERR! Please include the following file with any support request:
npm ERR!     /Users/igorganapolsky/workspace/git/ble/BluetoothLE-Examples/bleno/uribeacon/npm-debug.log

Is there any way to run this on a Mac?

Thanks,
Igor

**Comment by sandeepmistry** [comment]
@IgorGanapolsky uribeacon is really old, I suggest you take a look the node-eddystone-beacon: https://github.com/don/node-eddystone-beacon
